// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroAportes.Server.DAL;

#nullable disable

namespace RegistroAportes.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230313050228_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("RegistroAportes.Shared.Models.Aportes", b =>
                {
                    b.Property<int>("AporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Aporte")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AporteId");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("RegistroAportes.Shared.Models.AportesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AporteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoAporteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("DetalleId");

                    b.HasIndex("AporteId");

                    b.ToTable("AportesDetalle");
                });

            modelBuilder.Entity("RegistroAportes.Shared.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Total_Aportado")
                        .HasColumnType("REAL");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Cedula = "402-3362470-5",
                            Celular = "829-863-5107",
                            Fecha_Nacimiento = new DateOnly(2023, 3, 13),
                            Nombre = "Cesar",
                            Telefono = "829-986-6597",
                            Total_Aportado = 250.0
                        });
                });

            modelBuilder.Entity("RegistroAportes.Shared.Models.TipoAporte", b =>
                {
                    b.Property<int>("TipoAporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Logrado")
                        .HasColumnType("REAL");

                    b.Property<double>("Meta")
                        .HasColumnType("REAL");

                    b.HasKey("TipoAporteId");

                    b.ToTable("TiposAportes");
                });

            modelBuilder.Entity("RegistroAportes.Shared.Models.AportesDetalle", b =>
                {
                    b.HasOne("RegistroAportes.Shared.Models.Aportes", null)
                        .WithMany("DetalleAporte")
                        .HasForeignKey("AporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroAportes.Shared.Models.Aportes", b =>
                {
                    b.Navigation("DetalleAporte");
                });
#pragma warning restore 612, 618
        }
    }
}
